format = """
[](#1E1E2E)\
$python\
$username\
[](bg:#232634 fg:#1E1E2E)\
$directory\
[](fg:#232634 bg:#2A2D3A)\
$git_branch\
$git_status\
[](fg:#2A2D3A bg:#45475A)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#45475A bg:#B1B1D2)\
$docker_context\
[](fg:#B1B1D2 bg:#d5758a)\
$time\
[ ](fg:#d5758a)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

[username]
show_always = true
style_user = "bg:#1E1E2E"
style_root = "bg:#1E1E2E"
format = '[$user ]($style)'

[directory]
style = "bg:#232634"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#B1B1D2"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#2A2D3A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#2A2D3A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#1E1E2E"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#d5758a"
format = '[ $time ]($style)'
