# Alacritty Configuration

[window]
decorations = "none"  # Disable window decorations (no title bar, borders, etc.)
padding = { x = 20, y = 20 }  # Set margin of 10 on all sides
blur = true
dimensions = { columns = 90, lines = 30 }
opacity = 0.7

# Key bindings for copy and paste
[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },

    # Font size adjustments
    { key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "0", mods = "Control|Shift", action = "ResetFontSize" },

    # Scrolling
    { key = "PageUp", action = "ScrollPageUp" },
    { key = "PageDown", action = "ScrollPageDown" },
    { key = "Up", mods = "Control", action = "ScrollLineUp" },
    { key = "Down", mods = "Control", action = "ScrollLineDown" },

    # Window controls
    { key = "F11", action = "ToggleFullscreen" },
    { key = "F10", action = "Minimize" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
]

[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#888888"
bright_foreground = "#eaeaea"

[colors.cursor]
text = "#0f0f0f"
cursor = "#ff7b7b"

[colors.vi_mode_cursor]
text = "#0f0f0f"
cursor = "#ff5555"

[colors.search.matches]
foreground = "#0f0f0f"
background = "#ff8888"

[colors.search.focused_match]
foreground = "#0f0f0f"
background = "#ffaa55"

[colors.footer_bar]
foreground = "#0f0f0f"
background = "#666666"

[colors.hints.start]
foreground = "#0f0f0f"
background = "#ffa500"

[colors.hints.end]
foreground = "#0f0f0f"
background = "#55aaff"

[colors.selection]
text = "#0f0f0f"
background = "#ff99cc"

[colors.normal]
black = "#222222"
red = "#ff4444"
green = "#55ff55"
yellow = "#ffff55"
blue = "#5599ff"
magenta = "#ff55ff"
cyan = "#55ffff"
white = "#cccccc"

[colors.bright]
black = "#333333"
red = "#ff6666"
green = "#77ff77"
yellow = "#ffff77"
blue = "#77aaff"
magenta = "#ff77ff"
cyan = "#77ffff"
white = "#eeeeee"

[[colors.indexed_colors]]
index = 16
color = "#ff5555"

[[colors.indexed_colors]]
index = 17
color = "#ffaaff"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

bold = { family = "FiraCode Nerd Font", style = "Bold" }

italic = { family = "FiraCode Nerd Font", style = "Italic" }

bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 12
