# Alacritty Configuration

[window]
decorations = "none"  # Disable window decorations (no title bar, borders, etc.)
padding = { x = 20, y = 20 }  # Set margin of 10 on all sides
blur = true
dimensions = { columns = 90, lines = 30 }
opacity = 0.7

# Key bindings for copy and paste
[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },

    # Font size adjustments
    { key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "0", mods = "Control|Shift", action = "ResetFontSize" },

    # Scrolling
    { key = "PageUp", action = "ScrollPageUp" },
    { key = "PageDown", action = "ScrollPageDown" },
    { key = "Up", mods = "Control", action = "ScrollLineUp" },
    { key = "Down", mods = "Control", action = "ScrollLineDown" },

    # Window controls
    { key = "F11", action = "ToggleFullscreen" },
    { key = "F10", action = "Minimize" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
]

[colors.primary]
background = "#000000"
foreground = "#cdd6f4"
dim_foreground = "#6c7086"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#f38ba8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#6c7086"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#fab387"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#89b4fa"

[colors.selection]
text = "#1e1e2e"
background = "#f5c2e7"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#cdd6f4"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"


[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }

bold = { family = "FiraCode Nerd Font", style = "Bold" }

italic = { family = "FiraCode Nerd Font", style = "Italic" }

bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 15
